FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock* ./
RUN yarn install --frozen-lockfile || yarn install

COPY . .

EXPOSE 3000
ENV HOST=0.0.0.0 \
    PORT=3000 \
    WDS_SOCKET_PORT=0
CMD ["yarn", "start"]
